name: lil-4571000
channels:
- conda-forge
- defaults
dependencies:
- faker
- ipykernel
- ipywidgets
- lxml
- matplotlib
- numpy
- pandas
- plotly
- pyarrow
- pydantic
- python=3.12
- scikit-learn
- scipy
- seaborn
- statsmodels
- tables
